platform :ios, '9.0'

target 'TesstDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TesstDemo
    pod 'Masonry', '1.1.0'

end
